#!/bin/bash
# Generated by GitHub Copilot using Claude Haiku 4.5
# Description: Launch n8n with N|Solid runtime and telemetry
# This script configures N|Solid for OpenTelemetry export with OTLP

docker run -d \
  --name n8n-nsolid \
  -p 5678:5678 \
  -e NODE_ENV=production \
  -e NSOLID_APPNAME=n8n \
  -e NSOLID_TRACING_ENABLED=1 \
  -e NSOLID_OTLP=otlp \
  -e 'NSOLID_OTLP_CONFIG={"endpoints":{"metrics":"http://localhost:4318/v1/metrics","traces":"http://localhost:4318/v1/traces"}}' \
  -v n8n-data:/home/node/.n8n \
  n8n:nsolid-debian
