#!/bin/zsh
# N8N Docker startup script with Keychain credentials
# Generated by GitHub Copilot using Claude Sonnet 4.5
# This script retrieves n8n credentials from the Secure Enclave via Keychain
# and starts n8n in a Docker container with those credentials

set -e

# Retrieve credentials from Keychain entry "n8n"
# The password is stored in the Keychain entry
N8N_PASSWORD=$(security find-generic-password -s "n8n" -w 2>/dev/null)

# The username is stored as the account name in the Keychain entry
N8N_USERNAME=$(security find-generic-password -s "n8n" 2>&1 | grep "acct" | cut -d'"' -f4)

# Check if credentials were found
if [ -z "$N8N_PASSWORD" ] || [ -z "$N8N_USERNAME" ]; then
    echo "Error: Could not retrieve n8n credentials from Keychain entry 'n8n'"
    echo "Password found: $([ -n "$N8N_PASSWORD" ] && echo 'Yes' || echo 'No')"
    echo "Username found: $([ -n "$N8N_USERNAME" ] && echo 'Yes' || echo 'No')"
    if [ -n "$N8N_USERNAME" ]; then
        echo "Username: $N8N_USERNAME"
    fi
    exit 1
fi

echo "✓ Retrieved credentials from Secure Enclave (Keychain entry 'n8n')"

# Stop and remove existing container if it exists
docker stop n8n-local 2>/dev/null || true
docker rm n8n-local 2>/dev/null || true

# Create volume if it doesn't exist
docker volume create n8n_data 2>/dev/null || true

echo "✓ Docker environment prepared"
echo "Starting n8n in Docker..."

# Start n8n container with Keychain credentials
docker run -d \
  --name n8n-local \
  -p 5678:5678 \
  -e N8N_OWNER_EMAIL="$N8N_USERNAME" \
  -e N8N_OWNER_PASSWORD="$N8N_PASSWORD" \
  -e N8N_EDITOR_BASE_URL="http://localhost:5678" \
  -e N8N_LOG_LEVEL="info" \
  -v n8n_data:/home/node/.n8n \
  n8nio/n8n:local

# Wait for container to start
sleep 3

# Check container status
if docker ps --filter name=n8n-local --format '{{.Names}}' | grep -q n8n-local; then
    echo "✓ n8n container started successfully"
    echo ""
    echo "Container logs:"
    docker logs n8n-local
    echo ""
    echo "n8n is accessible at: http://localhost:5678"
    echo "Username: $N8N_USERNAME"
    echo ""
    echo "To view logs: docker logs -f n8n-local"
    echo "To stop: docker stop n8n-local"
else
    echo "✗ Failed to start n8n container"
    docker logs n8n-local 2>/dev/null || true
    exit 1
fi
