#!/bin/zsh
# N8N startup script that retrieves credentials from macOS Keychain
# Generated by GitHub Copilot
# This script retrieves n8n credentials from the Secure Enclave via Keychain
# and starts n8n with those credentials

set -e

# Retrieve credentials from Keychain entry "n8n"
# The password is stored in the Keychain entry
N8N_PASSWORD=$(security find-generic-password -s "n8n" -w 2>/dev/null)

# The username is stored as the account name in the Keychain entry
N8N_USERNAME=$(security find-generic-password -s "n8n" 2>&1 | grep "acct" | cut -d'"' -f4)

# Check if credentials were found
if [ -z "$N8N_PASSWORD" ] || [ -z "$N8N_USERNAME" ]; then
    echo "Error: Could not retrieve n8n credentials from Keychain entry 'n8n'"
    echo "Password found: $([ -n "$N8N_PASSWORD" ] && echo 'Yes' || echo 'No')"
    echo "Username found: $([ -n "$N8N_USERNAME" ] && echo 'Yes' || echo 'No')"
    if [ -n "$N8N_USERNAME" ]; then
        echo "Username: $N8N_USERNAME"
    fi
    exit 1
fi

echo "✓ Retrieved credentials from Secure Enclave (Keychain entry 'n8n')"

# Export environment variables for n8n
# These will be used to create/authenticate the owner account
export N8N_OWNER_EMAIL="$N8N_USERNAME"
export N8N_OWNER_PASSWORD="$N8N_PASSWORD"

# Optional: Set other useful environment variables
export N8N_EDITOR_BASE_URL="http://localhost:5678"
export N8N_LOG_LEVEL="info"

echo "✓ Environment variables configured"
echo "Starting n8n..."

# Start n8n with the credentials
cd /Users/danielgoldstein/Documents/VibeCoding/n8n
pnpm dev
