#!/bin/sh
# Generated by GitHub Copilot using Claude Sonnet 4.6
# Description: n8n Docker entrypoint using the N|Solid runtime.
# N|Solid is invoked explicitly so that the enhanced runtime (telemetry,
# CPU profiling, heap snapshots) is guaranteed regardless of shebang resolution.
if [ -d /opt/custom-certificates ]; then
  echo "Trusting custom certificates from /opt/custom-certificates."
  export NODE_OPTIONS="--use-openssl-ca $NODE_OPTIONS"
  export SSL_CERT_DIR=/opt/custom-certificates
  c_rehash /opt/custom-certificates
fi

if [ "$#" -gt 0 ]; then
  # Got started with arguments - prefer nsolid if available, else fallback to n8n CLI
  if command -v nsolid >/dev/null 2>&1; then
    exec nsolid /usr/local/lib/node_modules/n8n/bin/n8n "$@"
  else
    exec n8n "$@"
  fi
else
  # Got started without arguments
  if command -v nsolid >/dev/null 2>&1; then
    exec nsolid /usr/local/lib/node_modules/n8n/bin/n8n
  else
    exec n8n
  fi
fi
