#!/usr/bin/env bash
# Copilot generated by GitHub Copilot (Raptor mini).
# This script saves an n8n username and password pair in macOS Keychain.
# Usage: ./save-credentials-keychain.sh <service> <username> <password>
# Example: ./save-credentials-keychain.sh n8n user@example.com mysecret

set -euo pipefail

if [[ $# -ne 3 ]]; then
  echo "Usage: $0 <service> <username> <password>" >&2
  exit 1
fi

service="$1"
username="$2"
password="$3"

# Delete any existing item with same service/username to avoid duplicates
security delete-generic-password -s "$service" -a "$username" >/dev/null 2>&1 || true

# Add new generic password entry
security add-generic-password -s "$service" -a "$username" -w "$password" -U

echo "Credentials stored for service '$service' and user '$username' in Keychain."
